services:
  airflow:
    image: apache/airflow:3.1.3
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME
      AIRFLOW__CORE__FERNET_KEY: "YOUR_FERNET_KEY" # generate via: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./workflows/airflow_dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./infra/.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow scheduler & 
               airflow webserver"
    env_file:
      - ./infra/.env

  dbt:
    image: python:3.11-slim
    container_name: dbt
    working_dir: /usr/src/app
    volumes:
      - ./workflows/dbt:/usr/src/app
      - ./scripts:/usr/src/app/scripts
      - ./infra/.env:/usr/src/app/.env
    environment:
      DBT_PROFILES_DIR: /usr/src/app
    command: >
      bash -c "pip install --upgrade pip &&
               pip install dbt-core dbt-postgres psycopg2-binary &&
               tail -f /dev/null"
