services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    image: apache/airflow:3.1.3
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./workflows/airflow_dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./infra/.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db migrate &&
          airflow users create --username ${AIRFLOW_USER} --firstname Airflow --lastname Admin --role Admin --email admin@example.com --password ${AIRFLOW_PASSWORD} &&
          airflow scheduler &
          airflow api-webserver" # The webserver command is back for the UI, but the API is separate
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  dbt:
    image: python:3.11-slim
    container_name: dbt
    working_dir: /usr/src/app
    volumes:
      - ./workflows/dbt:/usr/src/app
      - ./scripts:/usr/src/app/scripts
      - ./infra/.env:/usr/src/app/.env
    environment:
      DBT_PROFILES_DIR: /usr/src/app
    env_file:
      - .env
    command: >
      bash -c "pip install --upgrade pip &&
               pip install dbt-core dbt-postgres psycopg2-binary &&
               tail -f /dev/null"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
